package handlers

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"aichat-api/database"
	"aichat-api/services"
	"aichat-api/utils"

	"github.com/gin-gonic/gin"
)

func TestMaintenanceConfigHandlerAutoGeneratesBypassKey(t *testing.T) {
	gin.SetMode(gin.TestMode)
	if err := database.Init(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if db := database.Get(); db != nil {
			_ = db.Close()
		}
	})

	router := gin.New()
	handler := &AdminHandler{}
	router.GET("/mc", handler.GetMaintenanceConfig)
	router.PUT("/mc", handler.UpdateMaintenanceConfig)

	// 开启且 Key 留空 → 服务端自动生成随机 Key 并返回
	req := httptest.NewRequest(http.MethodPut, "/mc", bytes.NewBufferString(`{"enabled":true,"bypass_key":""}`))
	req.Header.Set("Content-Type", "application/json")
	recorder := httptest.NewRecorder()
	router.ServeHTTP(recorder, req)

	var putResp utils.Response
	if err := json.Unmarshal(recorder.Body.Bytes(), &putResp); err != nil {
		t.Fatal(err)
	}
	if putResp.Code != utils.CodeSuccess {
		t.Fatalf("PUT response code = %d body = %s", putResp.Code, recorder.Body.String())
	}

	enabled, key := services.GetMaintenanceConfig()
	if !enabled {
		t.Fatal("expected maintenance enabled after PUT")
	}
	if key == "" {
		t.Fatal("expected auto-generated bypass key, got empty")
	}

	// GET 返回相同配置
	getReq := httptest.NewRequest(http.MethodGet, "/mc", nil)
	getRecorder := httptest.NewRecorder()
	router.ServeHTTP(getRecorder, getReq)
	var getResp struct {
		Code int `json:"code"`
		Data struct {
			Enabled   bool   `json:"enabled"`
			BypassKey string `json:"bypass_key"`
		} `json:"data"`
	}
	if err := json.Unmarshal(getRecorder.Body.Bytes(), &getResp); err != nil {
		t.Fatal(err)
	}
	if getResp.Code != utils.CodeSuccess || !getResp.Data.Enabled || getResp.Data.BypassKey != key {
		t.Fatalf("GET mismatch: %+v (want enabled=true key=%q)", getResp, key)
	}
}

func TestMaintenanceConfigHandlerDisableKeepsKey(t *testing.T) {
	gin.SetMode(gin.TestMode)
	if err := database.Init(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if db := database.Get(); db != nil {
			_ = db.Close()
		}
	})

	router := gin.New()
	handler := &AdminHandler{}
	router.PUT("/mc", handler.UpdateMaintenanceConfig)

	req := httptest.NewRequest(http.MethodPut, "/mc", bytes.NewBufferString(`{"enabled":false,"bypass_key":"mykey"}`))
	req.Header.Set("Content-Type", "application/json")
	recorder := httptest.NewRecorder()
	router.ServeHTTP(recorder, req)

	var resp utils.Response
	if err := json.Unmarshal(recorder.Body.Bytes(), &resp); err != nil {
		t.Fatal(err)
	}
	if resp.Code != utils.CodeSuccess {
		t.Fatalf("PUT response code = %d body = %s", resp.Code, recorder.Body.String())
	}

	enabled, key := services.GetMaintenanceConfig()
	if enabled {
		t.Fatal("expected maintenance disabled after PUT")
	}
	if key != "mykey" {
		t.Fatalf("bypass key = %q, want mykey", key)
	}
}
